### PR TITLE
Ch02

### PR DESCRIPTION
**Pull request by GuidoS**
Hi,

I was wondering if you would like some help with the update/creation of chapter by chapter code. I am going through this book quickly and going back and making this code presentable for the public is helping me make sure I know what's going on. And since I am doing the work, why not share.

Let me know if you want this or not.

### CODE REVIEW

**Comment by EthanRBrown** [comment]
Hi, Guido; I'm sorry this has taken me so long to respond to.  I've been swamped with my various responsibilities, and I'm sad to say that WDNE has been getting short shrift.  I _would_ like help (who wouldn't like free help?).  The problem is, it gets complicated when you have books out there saying one thing and a repo saying another.  Obviously the repo should be the "authority" and should represent up-to-date thinking (otherwise why have it, other than a cut & paste vehicle?).  I'm just struggling to figure out how to balance these two needs.  Also complicating the matter is that I'm updating the book itself...so oy!  Very complicated.  I'll review your PR, and thank you so much for your efforts and consideration.

**Comment by GuidoS** [comment]
ok, I totally understand. I will continue doing what I am doing, if it is of use to you enjoy.. ;)

**Comment by EthanRBrown** [comment]
If you would like to give me some feedback on the new direction I want to take with the repo, I am open!  You can read about it on the updated [README](https://github.com/EthanRBrown/web-development-with-node-and-express).

**Comment by GuidoS** [comment]
I left some notes about the new direction on the repo commit for the new
readme, I hope that helps.

**Comment by EthanRBrown** [comment]
Thanks, Guido, it is helpful!

**Pull request closed without merging**
